const postConstants = {
  CREATE_POST: 'CREATE_POST',
  UPDATE_POST: 'UPDATE_POST',
  DELETE_POST: 'DELETE_POST',
  GET_ONE_POST: 'GET_ONE_POST',

  LIKE_POST: 'LIKE_POST',
  DISLIKE_POST: 'DISLIKE_POST',
  COMMENT: 'COMMENT',
};

export default postConstants;
